// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP8M4afpQsabhN2fdyZ-jwRD1k4Wrbbz4',
    appId: '1:260671669952:web:0bca88a0281b61b1954f25',
    messagingSenderId: '260671669952',
    projectId: 'stepup-a0ed7',
    authDomain: 'stepup-a0ed7.firebaseapp.com',
    storageBucket: 'stepup-a0ed7.appspot.com',
    measurementId: 'G-DXPY0BDGZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB38DTfXuuiGgHHX46x6cAXUJYu5atD3Gg',
    appId: '1:260671669952:android:60fca66cf2c672a9954f25',
    messagingSenderId: '260671669952',
    projectId: 'stepup-a0ed7',
    storageBucket: 'stepup-a0ed7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa6Q5ft5Fb3FKryaWKNV9z2bVrEWUNn6E',
    appId: '1:260671669952:ios:9b70e042330b24ca954f25',
    messagingSenderId: '260671669952',
    projectId: 'stepup-a0ed7',
    storageBucket: 'stepup-a0ed7.appspot.com',
    androidClientId: '260671669952-3rntq588jghm402pgbddija6e3i1bflu.apps.googleusercontent.com',
    iosClientId: '260671669952-mioskr5h84m88bhpsdl4tmk5ortmuht5.apps.googleusercontent.com',
    iosBundleId: 'com.example.trail2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa6Q5ft5Fb3FKryaWKNV9z2bVrEWUNn6E',
    appId: '1:260671669952:ios:9b70e042330b24ca954f25',
    messagingSenderId: '260671669952',
    projectId: 'stepup-a0ed7',
    storageBucket: 'stepup-a0ed7.appspot.com',
    androidClientId: '260671669952-3rntq588jghm402pgbddija6e3i1bflu.apps.googleusercontent.com',
    iosClientId: '260671669952-mioskr5h84m88bhpsdl4tmk5ortmuht5.apps.googleusercontent.com',
    iosBundleId: 'com.example.trail2',
  );
}
